version: '3.9'
services:
    malbot:
        image: ghcr.io/malbryn/malbot:1.6.0
        container_name: malbot
        volumes:
            - /var/local/malbot/config:/app/config
            - /var/local/malbot/data:/app/data
