version: '3.9'
services:
    malbot:
        image: ghcr.io/malbryn/malbot:1.4.2
        container_name: malbot
        volumes:
            - /var/local/malbot/config:/app/config
        restart: unless-stopped
