services:
  malbot:
    image: ghcr.io/malbryn/malbot:latest
    container_name: malbot
    restart: unless-stopped
    volumes:
      - /var/local/malbot/config:/app/config
      - /var/local/malbot/data:/app/data
